### ISSUE TITLE
Disabling "Enable Style" still produces style warnings

### ISSUE THREAD

**Issue by stephen-d-hill** [Munkei/atom-linter-cppcheck#3] opened 2016-10-05 09:58 UTC
Disabling "Enable Style" still produces style warnings.
Am using CppCheck v1.75.

**Comment by biffen** [comment] 2016-10-05 10:54
I can't reproduce this (Cppcheck v1.75). Using a file with a style error, disabling and enabling _Enable Style_ makes the warning disappear and reappear, respectively (after saving, causing Cppcheck to run).

Could you provide a sample of code that produces this error?

And if possible, could you run `until pgrep -a cppcheck ; do : ; done` in a terminal, then run _Linter: Lint_ in Atom, then post whatever shows up in the terminal?

**Comment by stephen-d-hill** [comment] 2016-10-06 08:21
I'm running in M$-Windows 7...I suspect that's the difference!

**Comment by biffen** [comment] 2016-10-06 09:42
I've now tried the same on Windows (10), and I still can't reproduce.

I'd need some more information before I could even attempt to solve this.
1. What have you set as the executable? In fact, I'd like to see _all_ the settings for `linter-cppcheck`.
2. Could you provide a screenshot of the code and the linter warning?

**Comment by stephen-d-hill** [comment] 2016-10-06 12:18
[image: Inline images 2]

[image: Inline images 1]

​

**Comment by biffen** [comment] 2016-10-06 12:21
The images don't actually show up. Would you mind editing or re-posting (perhaps through the GitHub website, rather than email)?

**Comment by stephen-d-hill** [comment] 2016-10-07 12:37
Here's my settings:

  linter:
    errorPanelHeight: 320
  "linter-cppcheck":
    enableInformation: false
    enableStyle: false
    enableWarning: false
    executable: "C:\Program Files\Cppcheck\cppcheck"

**Comment by biffen** [comment] 2016-10-18 08:04
Copied those settings; can't reproduce. I use the following code:

``` c++
int main() {
  float f = false;
}
```

Could you post code that causes the issue for you?

If I can't reproduce this I'm afraid I'll have to close this issue.

**Comment by biffen** [comment] 2016-10-25 13:27
I'm closing this now as I can't reproduce it and I'm not getting enough information to even begin trying to solve it.

**Closed as completed by biffen** 2016-10-25 13:27 UTC
Labels: bug, needs-reproduced
